from langchain.agents import Tool
from htmlTemplates import css, bot_template, user_template, disclaimer_text, box_template, user_img, bot_img
from typing import List
from langchain.agents import Tool
from streamlit.components.v1 import html
from agentFunctions import simple_report_search, report_summarizer, one_person_search, more_person_search

def create_tools():
    # define usable Tools for the Agent
    tools = [
        Tool(
            name = "SimpleReportSearch",
            func=simple_report_search,
            description="useful if you think that you need just a little information from the MPI Research Report 2023 to answer the User Question. Input a question and keywords generated by you, Suitable for a keyword-based search in a vector space"
        ),
        Tool(
            name = "ReportSummarizer",
            func = report_summarizer,
            description="useful if you think that you need a lot information from the MPI Research Report 2023 to answer the User Question. Input a question and keywords generated by you, Suitable for a keyword-based search in a vector space"
        ),
        Tool(
            name = "OnePersonSearch",
            func= one_person_search,
            description="useful if you think that you need personal information about only one persons in the MPI to answer the User Question. It will include references for Selected Literature of this person aswell. Input a question and the name of the person, Suitable for a keyword-based search in a vector space"
        ),
        Tool(
            name = "MorePersonSearch",
            func=more_person_search,
            description="useful if you think that you need personal information about more then one persons in the MPI to answer the User Question. It will list references for Selected Literature of this person aswell. Input a question and all names of all the persons, Suitable for a keyword-based search in a vector space"
        )
    ]
    return tools
