version: '3.4'

# Definiere das gemeinsame Verhalten
x-minervasarchive:
  &default-minervasarchive
  build:
    dockerfile: Dockerfile
    secrets:
      - env
    args:
      REPO: https://github.com/formal-methods-mpi/MinervasArchive
      BRANCH: Main
  env_file:
    - .env
  ports:
    - "8501:8501"

services:
  # Image Tag für latest
  minervasarchive:
    <<: *default-minervasarchive
    image: ghcr.io/formal-methods-mpi/minervasarchive:latest

  # Image Tag für version
  minervasarchive_version:
    <<: *default-minervasarchive
    image: ghcr.io/formal-methods-mpi/minervasarchive:0.2.0

secrets:
  env:
    file: ./.env